package selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Unit test for simple App.
 */
public class AppTest 
{
    
    private WebDriver driver;

    @Before
    public void setUp(){
        System.out.println("Iniciando configuración...");
        System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
        driver = new ChromeDriver();
    }

    @Test
    public void prueba(){
        DateFormat dateFormat = new SimpleDateFormat("yyyyMMddhhmmss");
        Date date = new Date();
        String date1= dateFormat.format(date);
        String mail="a@m"+date1+".com";
        String name="José";
        String lastName="Lopez";
        String company="Karibu";
        String address1="San Francisco";
        String address2="467";
        String city="Santiago";
        String phone="12345679";
        String phone_mobile="12345678";
        String postcode = "12345";
        String state = "Connecticut";
        driver.get("http://automationpractice.com/index.php");
        driver.manage().window().maximize();
        driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .replace-2x")).click(); 
        driver.findElement(By.cssSelector(".exclusive > span")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.findElement(By.cssSelector(".button-medium > span")).click();
        driver.findElement(By.cssSelector(".standard-checkout > span")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.findElement(By.id("email_create")).click();
        driver.findElement(By.id("email_create")).sendKeys(mail);
        driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
        driver.findElement(By.id("id_gender1")).click();
        driver.findElement(By.id("customer_firstname")).click();
        driver.findElement(By.id("customer_firstname")).sendKeys(name);
        driver.findElement(By.id("customer_lastname")).click();
        driver.findElement(By.id("customer_lastname")).sendKeys(lastName);
        driver.findElement(By.id("email")).click();
        driver.findElement(By.cssSelector(".password")).click();
        driver.findElement(By.id("passwd")).click();
        driver.findElement(By.id("passwd")).sendKeys("12345");
        driver.findElement(By.cssSelector(".account_creation:nth-child(1)")).click();
        driver.findElement(By.id("days")).click();
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        driver.findElement(By.xpath("//*[@id='days']/option[6]")).click();
        driver.findElement(By.id("months")).click();
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        driver.findElement(By.xpath("//*[@id='months']/option[5]")).click();
        driver.findElement(By.id("years")).click();
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        driver.findElement(By.xpath("//*[@id='years']/option[7]")).click();
        driver.findElement(By.id("company")).click();
        driver.findElement(By.id("company")).sendKeys(company);
        driver.findElement(By.id("address1")).click();
        driver.findElement(By.id("address1")).sendKeys(address1);
        driver.findElement(By.cssSelector(".is_customer_param > .inline-infos")).click();
        driver.findElement(By.id("address2")).click();
        driver.findElement(By.id("address2")).sendKeys(address2);
        driver.findElement(By.id("city")).click();
        driver.findElement(By.id("city")).sendKeys(city);
        driver.findElement(By.id("id_state")).click();
        {
          WebElement dropdown = driver.findElement(By.id("id_state"));
          dropdown.findElement(By.xpath("//option[. = '"+state+"']")).click();
        }
        driver.findElement(By.cssSelector("#id_country > option:nth-child(2)")).click();
        String country = driver.findElement(By.xpath("//*[@id='id_country']/option[2]")).getText();
        driver.findElement(By.id("postcode")).click();
        driver.findElement(By.id("postcode")).sendKeys(postcode);
        driver.findElement(By.id("other")).click();
        driver.findElement(By.id("other")).sendKeys("hola");
        driver.findElement(By.id("phone")).click();
        driver.findElement(By.id("phone")).sendKeys(phone);
        driver.findElement(By.id("phone_mobile")).click();
        driver.findElement(By.id("phone_mobile")).sendKeys(phone_mobile);
        driver.findElement(By.cssSelector("#submitAccount > span")).click();
        String validate1 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[2]")).getText();
        String validate2 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[3]")).getText();
        String validate3 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[4]")).getText();
        String validate4 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[5]")).getText();
        String validate5 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[6]")).getText();
        String validate6 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[7]")).getText();
        String validate7 = driver.findElement(By.xpath("//*[@id='address_delivery']/li[8]")).getText();
        assertEquals(name +" "+lastName, validate1);
        assertEquals(company, validate2);
        assertEquals(address1 + " " + address2, validate3);
        assertEquals(city +", "+ state +" "+postcode, validate4);
        assertEquals(country, validate5);
        assertEquals(phone, validate6);
        assertEquals(phone_mobile, validate7);
        validate1 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[2]")).getText();
        validate2 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[3]")).getText();
        validate3 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[4]")).getText();
        validate4 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[5]")).getText();
        validate5 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[6]")).getText();
        validate6 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[7]")).getText();
        validate7 = driver.findElement(By.xpath("//*[@id='address_invoice']/li[8]")).getText();
        assertEquals(name +" "+lastName, validate1);
        assertEquals(company, validate2);
        assertEquals(address1 + " " + address2, validate3);
        assertEquals(city +", "+ state +" "+postcode, validate4);
        assertEquals(country, validate5);
        assertEquals(phone, validate6);
        assertEquals(phone_mobile, validate7);
        driver.findElement(By.xpath("//*[@id='center_column']/form/p/button/span")).click();
        driver.findElement(By.id("cgv")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.findElement(By.cssSelector(".standard-checkout > span")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.findElement(By.cssSelector("#cart_navigation span")).click();
    }
    @After
    public void tearDown() {
        driver.close(); // Cierra el navegador actual abierto por el Script 
        driver.quit();  // Cierra todas las sesiones abiertas por el Script
    }
}